- name : creating a user 
  user : 
    name : "{{app_user}}"
    state : present 

- name : installing java 
  yum :
    name : java
    state : present 


- name : getting tomcat latest version 
  shell : curl -s http://tomcat.apache.org/ | grep Released | grep "Tomcat [0-9]" | awk '{print $(NF-1)}' | grep ^8
  register : out 


- name : set tomcat facts
  set_fact :
    TOMCAT_HOME : "/home/{{app_user}}/apache-tomcat-{{out.stdout}}"
    app_home : "/home/{{app_user}}"


- name : installing tomcat on student user
  unarchive : 
      src : https://archive.apache.org/dist/tomcat/tomcat-8/v{{out.stdout}}/bin/apache-tomcat-{{out.stdout}}.tar.gz
      dest : "{{app_home}}"
      remote_src : yes
  become_user : "{{app_user}}"



- name : adding application on student user
  get_url :
    url : https://s3-us-west-2.amazonaws.com/studentapi-cit/student.war
    dest : "{{TOMCAT_HOME}}/webapps/student.war"
    remote_src : yes
  become_user : "{{app_user}}"


- name : starting tomcat server
  shell : "{{TOMCAT_HOME}}/bin/startup.sh"