- name : creating a user 
  user : 
    name : "{{app_user}}"
    state : present 

- name : installing java 
  yum :
    name : java
    state : present 


- name : getting tomcat latest version 
  shell : curl -s http://tomcat.apache.org/ | grep Released | grep "Tomcat [0-9]" | awk '{print $(NF-1)}' | grep ^8
  register : out 


- name : set tomcat facts
  set_fact :
    TOMCAT_HOME : "/home/{{app_user}}/apache-tomcat-{{out.stdout}}"
    app_home : "/home/{{app_user}}"


- name : installing tomcat on student user
  unarchive : 
      src : https://archive.apache.org/dist/tomcat/tomcat-8/v{{out.stdout}}/bin/apache-tomcat-{{out.stdout}}.tar.gz
      dest : "{{app_home}}"
      remote_src : yes
  become_user : "{{app_user}}"



- name : adding application on student user
  get_url :
    url : https://s3-us-west-2.amazonaws.com/studentapi-cit/student.war
    dest : "{{TOMCAT_HOME}}/webapps/student.war"
    remote_src : yes
  become_user : "{{app_user}}"


- name : starting tomcat server
  shell : "{{TOMCAT_HOME}}/bin/startup.sh"

- name : database connection jar file
  get_url : 
    url : https://s3-us-west-2.amazonaws.com/studentapi-cit/mysql-connector.jar
    dest : "{{TOMCAT_HOME}}/lib/mysql-connector.jar"
    remote_src : yes
  become_user : "{{app_user}}"


- name : updating context.xml file
  blockinfile:
        path : "{{TOMCAT_HOME}}/conf/context.xml"
        insertbefore : "</Context>"
        block : |
            <Resource name="jdbc/TestDB" auth="Container" type="javax.sql.DataSource"
               maxTotal="100" maxIdle="30" maxWaitMillis="10000"
               username="{{DB_USER}}" password="{{DB_PASS}}" driverClassName="com.mysql.jdbc.Driver"
               url="jdbc:mysql://{{DB_HOST}}:3306/{{DB_NAME}}"/>
  become_user : "{{app_user}}"

- name : restarting tomcat server
  shell : "{{TOMCAT_HOME}}/bin/startup.sh"

- name : create api directory 
  file :
    path : "{{app_home}}/api"
    state : directory
  become_user : "{{app_user}}"


- name : copying db details env file
  template :
    src : roles/appserver/template/db-details
    dest : "{{app_home}}/api/.db-details"
  become_user : "{{app_user}}"


- name : adding a line to import file
  lineinfile:
        path : "{{app_home}}/.bash_profile"
        line : "source {{app_home}}/api/.db-details"

- name : download student war file
  get_url :
    url : https://s3-us-west-2.amazonaws.com/studentapi-cit/studentapi.war
    dest : "{{app_home}}/api/student.war"
    remote_src : yes 

- name : download studentapi init script 
  get_url :
    url : https://s3-us-west-2.amazonaws.com/studentapi-cit/studentapi-init
    dest : /etc/init.d/studentapi
    remote_src : yes
    mode : 0755


- name : reload systemctl daemon
  shell : systemctl daemon-reload 


- name : starting student api
    service :
      name : studentapi 
      state : restarted
      enabled : yes





